##################### Style ##################################
Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  EnforcedStyle: compact

Style/Encoding:
  EnforcedStyle: when_needed

Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Description: "Keeps track of empty lines around class bodies."
  EnforcedStyle: empty_lines

Style/RegexpLiteral:
  Description: 'Use / or %r around regular expressions.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-r'
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SignalException:
  Description: 'Checks for proper usage of fail and raise.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#prefer-raise-over-fail'
  EnforcedStyle: only_raise

Style/CaseIndentation:
  Description: 'Indentation of when in a case/when/[else/]end.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#indent-when-to-case'
  IndentWhenRelativeTo: case
  IndentOneStep: true

Style/RedundantBegin:
  Description: "Don't use begin blocks when they are not needed."
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#begin-implicit'
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

##################### Metrics ##################################
Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 150

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#short-methods'
  CountComments: false  # count full line comments?
  Max: 50

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  CountComments: false  # count full line comments?
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 50